import { ComponentPropsWithRef, FC, HTMLAttributes, RefObject } from 'react';

import { XProps } from '../../types/common';

export type TagNameComponentMap = {
  // HTML
  a: FC<ComponentPropsWithRef<'a'> & XProps>;
  abbr: FC<ComponentPropsWithRef<'abbr'> & XProps>;
  address: FC<ComponentPropsWithRef<'address'> & XProps>;
  area: FC<ComponentPropsWithRef<'area'> & XProps>;
  article: FC<ComponentPropsWithRef<'article'> & XProps>;
  aside: FC<ComponentPropsWithRef<'aside'> & XProps>;
  audio: FC<ComponentPropsWithRef<'audio'> & XProps>;
  b: FC<ComponentPropsWithRef<'b'> & XProps>;
  base: FC<ComponentPropsWithRef<'base'> & XProps>;
  bdi: FC<ComponentPropsWithRef<'bdi'> & XProps>;
  bdo: FC<ComponentPropsWithRef<'bdo'> & XProps>;
  big: FC<ComponentPropsWithRef<'big'> & XProps>;
  blockquote: FC<ComponentPropsWithRef<'blockquote'> & XProps>;
  body: FC<ComponentPropsWithRef<'body'> & XProps>;
  br: FC<ComponentPropsWithRef<'br'> & XProps>;
  button: FC<ComponentPropsWithRef<'button'> & XProps>;
  canvas: FC<ComponentPropsWithRef<'canvas'> & XProps>;
  caption: FC<ComponentPropsWithRef<'caption'> & XProps>;
  center: FC<ComponentPropsWithRef<'center'> & XProps>;
  cite: FC<ComponentPropsWithRef<'cite'> & XProps>;
  code: FC<ComponentPropsWithRef<'code'> & XProps>;
  col: FC<ComponentPropsWithRef<'col'> & XProps>;
  colgroup: FC<ComponentPropsWithRef<'colgroup'> & XProps>;
  data: FC<ComponentPropsWithRef<'data'> & XProps>;
  datalist: FC<ComponentPropsWithRef<'datalist'> & XProps>;
  dd: FC<ComponentPropsWithRef<'dd'> & XProps>;
  del: FC<ComponentPropsWithRef<'del'> & XProps>;
  details: FC<ComponentPropsWithRef<'details'> & XProps>;
  dfn: FC<ComponentPropsWithRef<'dfn'> & XProps>;
  dialog: FC<ComponentPropsWithRef<'dialog'> & XProps>;
  div: FC<ComponentPropsWithRef<'div'> & XProps>;
  dl: FC<ComponentPropsWithRef<'dl'> & XProps>;
  dt: FC<ComponentPropsWithRef<'dt'> & XProps>;
  em: FC<ComponentPropsWithRef<'em'> & XProps>;
  embed: FC<ComponentPropsWithRef<'embed'> & XProps>;
  fieldset: FC<ComponentPropsWithRef<'fieldset'> & XProps>;
  figcaption: FC<ComponentPropsWithRef<'figcaption'> & XProps>;
  figure: FC<ComponentPropsWithRef<'figure'> & XProps>;
  footer: FC<ComponentPropsWithRef<'footer'> & XProps>;
  form: FC<ComponentPropsWithRef<'form'> & XProps>;
  h1: FC<ComponentPropsWithRef<'h1'> & XProps>;
  h2: FC<ComponentPropsWithRef<'h2'> & XProps>;
  h3: FC<ComponentPropsWithRef<'h3'> & XProps>;
  h4: FC<ComponentPropsWithRef<'h4'> & XProps>;
  h5: FC<ComponentPropsWithRef<'h5'> & XProps>;
  h6: FC<ComponentPropsWithRef<'h6'> & XProps>;
  head: FC<ComponentPropsWithRef<'head'> & XProps>;
  header: FC<ComponentPropsWithRef<'header'> & XProps>;
  hgroup: FC<ComponentPropsWithRef<'hgroup'> & XProps>;
  hr: FC<ComponentPropsWithRef<'hr'> & XProps>;
  html: FC<ComponentPropsWithRef<'html'> & XProps>;
  i: FC<ComponentPropsWithRef<'i'> & XProps>;
  iframe: FC<ComponentPropsWithRef<'iframe'> & XProps>;
  img: FC<ComponentPropsWithRef<'img'> & XProps>;
  input: FC<ComponentPropsWithRef<'input'> & XProps>;
  ins: FC<ComponentPropsWithRef<'ins'> & XProps>;
  kbd: FC<ComponentPropsWithRef<'kbd'> & XProps>;
  keygen: FC<ComponentPropsWithRef<'keygen'> & XProps>;
  label: FC<ComponentPropsWithRef<'label'> & XProps>;
  legend: FC<ComponentPropsWithRef<'legend'> & XProps>;
  li: FC<ComponentPropsWithRef<'li'> & XProps>;
  link: FC<ComponentPropsWithRef<'link'> & XProps>;
  main: FC<ComponentPropsWithRef<'main'> & XProps>;
  map: FC<ComponentPropsWithRef<'map'> & XProps>;
  mark: FC<ComponentPropsWithRef<'mark'> & XProps>;
  menu: FC<ComponentPropsWithRef<'menu'> & XProps>;
  menuitem: FC<ComponentPropsWithRef<'menuitem'> & XProps>;
  meta: FC<ComponentPropsWithRef<'meta'> & XProps>;
  meter: FC<ComponentPropsWithRef<'meter'> & XProps>;
  nav: FC<ComponentPropsWithRef<'nav'> & XProps>;
  noindex: FC<ComponentPropsWithRef<'noindex'> & XProps>;
  noscript: FC<ComponentPropsWithRef<'noscript'> & XProps>;
  object: FC<ComponentPropsWithRef<'object'> & XProps>;
  ol: FC<ComponentPropsWithRef<'ol'> & XProps>;
  optgroup: FC<ComponentPropsWithRef<'optgroup'> & XProps>;
  option: FC<ComponentPropsWithRef<'option'> & XProps>;
  output: FC<ComponentPropsWithRef<'output'> & XProps>;
  p: FC<ComponentPropsWithRef<'p'> & XProps>;
  param: FC<ComponentPropsWithRef<'param'> & XProps>;
  picture: FC<ComponentPropsWithRef<'picture'> & XProps>;
  pre: FC<ComponentPropsWithRef<'pre'> & XProps>;
  progress: FC<ComponentPropsWithRef<'progress'> & XProps>;
  q: FC<ComponentPropsWithRef<'q'> & XProps>;
  rp: FC<ComponentPropsWithRef<'rp'> & XProps>;
  rt: FC<ComponentPropsWithRef<'rt'> & XProps>;
  ruby: FC<ComponentPropsWithRef<'ruby'> & XProps>;
  s: FC<ComponentPropsWithRef<'s'> & XProps>;
  samp: FC<ComponentPropsWithRef<'samp'> & XProps>;
  search: FC<ComponentPropsWithRef<'search'> & XProps>;
  slot: FC<ComponentPropsWithRef<'slot'> & XProps>;
  script: FC<ComponentPropsWithRef<'script'> & XProps>;
  section: FC<ComponentPropsWithRef<'section'> & XProps>;
  select: FC<ComponentPropsWithRef<'select'> & XProps>;
  small: FC<ComponentPropsWithRef<'small'> & XProps>;
  source: FC<ComponentPropsWithRef<'source'> & XProps>;
  span: FC<ComponentPropsWithRef<'span'> & XProps>;
  strong: FC<ComponentPropsWithRef<'strong'> & XProps>;
  style: FC<ComponentPropsWithRef<'style'> & XProps>;
  sub: FC<ComponentPropsWithRef<'sub'> & XProps>;
  summary: FC<ComponentPropsWithRef<'summary'> & XProps>;
  sup: FC<ComponentPropsWithRef<'sup'> & XProps>;
  table: FC<ComponentPropsWithRef<'table'> & XProps>;
  template: FC<ComponentPropsWithRef<'template'> & XProps>;
  tbody: FC<ComponentPropsWithRef<'tbody'> & XProps>;
  td: FC<ComponentPropsWithRef<'td'> & XProps>;
  textarea: FC<ComponentPropsWithRef<'textarea'> & XProps>;
  tfoot: FC<ComponentPropsWithRef<'tfoot'> & XProps>;
  th: FC<ComponentPropsWithRef<'th'> & XProps>;
  thead: FC<ComponentPropsWithRef<'thead'> & XProps>;
  time: FC<ComponentPropsWithRef<'time'> & XProps>;
  title: FC<ComponentPropsWithRef<'title'> & XProps>;
  tr: FC<ComponentPropsWithRef<'tr'> & XProps>;
  track: FC<ComponentPropsWithRef<'track'> & XProps>;
  u: FC<ComponentPropsWithRef<'u'> & XProps>;
  ul: FC<ComponentPropsWithRef<'ul'> & XProps>;
  var: FC<ComponentPropsWithRef<'var'> & XProps>;
  video: FC<ComponentPropsWithRef<'video'> & XProps>;
  wbr: FC<ComponentPropsWithRef<'wbr'> & XProps>;
  webview: FC<ComponentPropsWithRef<'webview'> & XProps>;

  // SVG
  svg: FC<ComponentPropsWithRef<'svg'> & XProps>;

  animate: FC<ComponentPropsWithRef<'animate'> & XProps>;
  animateMotion: FC<ComponentPropsWithRef<'animateMotion'> & XProps>;
  animateTransform: FC<ComponentPropsWithRef<'animateTransform'> & XProps>;
  circle: FC<ComponentPropsWithRef<'circle'> & XProps>;
  clipPath: FC<ComponentPropsWithRef<'clipPath'> & XProps>;
  defs: FC<ComponentPropsWithRef<'defs'> & XProps>;
  desc: FC<ComponentPropsWithRef<'desc'> & XProps>;
  ellipse: FC<ComponentPropsWithRef<'ellipse'> & XProps>;
  feBlend: FC<ComponentPropsWithRef<'feBlend'> & XProps>;
  feColorMatrix: FC<ComponentPropsWithRef<'feColorMatrix'> & XProps>;
  feComponentTransfer: FC<
    ComponentPropsWithRef<'feComponentTransfer'> & XProps
  >;
  feComposite: FC<ComponentPropsWithRef<'feComposite'> & XProps>;
  feConvolveMatrix: FC<ComponentPropsWithRef<'feConvolveMatrix'> & XProps>;
  feDiffuseLighting: FC<ComponentPropsWithRef<'feDiffuseLighting'> & XProps>;
  feDisplacementMap: FC<ComponentPropsWithRef<'feDisplacementMap'> & XProps>;
  feDistantLight: FC<ComponentPropsWithRef<'feDistantLight'> & XProps>;
  feDropShadow: FC<ComponentPropsWithRef<'feDropShadow'> & XProps>;
  feFlood: FC<ComponentPropsWithRef<'feFlood'> & XProps>;
  feFuncA: FC<ComponentPropsWithRef<'feFuncA'> & XProps>;
  feFuncB: FC<ComponentPropsWithRef<'feFuncB'> & XProps>;
  feFuncG: FC<ComponentPropsWithRef<'feFuncG'> & XProps>;
  feFuncR: FC<ComponentPropsWithRef<'feFuncR'> & XProps>;
  feGaussianBlur: FC<ComponentPropsWithRef<'feGaussianBlur'> & XProps>;
  feImage: FC<ComponentPropsWithRef<'feImage'> & XProps>;
  feMerge: FC<ComponentPropsWithRef<'feMerge'> & XProps>;
  feMergeNode: FC<ComponentPropsWithRef<'feMergeNode'> & XProps>;
  feMorphology: FC<ComponentPropsWithRef<'feMorphology'> & XProps>;
  feOffset: FC<ComponentPropsWithRef<'feOffset'> & XProps>;
  fePointLight: FC<ComponentPropsWithRef<'fePointLight'> & XProps>;
  feSpecularLighting: FC<ComponentPropsWithRef<'feSpecularLighting'> & XProps>;
  feSpotLight: FC<ComponentPropsWithRef<'feSpotLight'> & XProps>;
  feTile: FC<ComponentPropsWithRef<'feTile'> & XProps>;
  feTurbulence: FC<ComponentPropsWithRef<'feTurbulence'> & XProps>;
  filter: FC<ComponentPropsWithRef<'filter'> & XProps>;
  foreignObject: FC<ComponentPropsWithRef<'foreignObject'> & XProps>;
  g: FC<ComponentPropsWithRef<'g'> & XProps>;
  image: FC<ComponentPropsWithRef<'image'> & XProps>;
  line: React.SVGLineElementAttributes<SVGLineElement>;
  linearGradient: FC<ComponentPropsWithRef<'linearGradient'> & XProps>;
  marker: FC<ComponentPropsWithRef<'marker'> & XProps>;
  mask: FC<ComponentPropsWithRef<'mask'> & XProps>;
  metadata: FC<ComponentPropsWithRef<'metadata'> & XProps>;
  mpath: FC<ComponentPropsWithRef<'mpath'> & XProps>;
  path: FC<ComponentPropsWithRef<'path'> & XProps>;
  pattern: FC<ComponentPropsWithRef<'pattern'> & XProps>;
  polygon: FC<ComponentPropsWithRef<'polygon'> & XProps>;
  polyline: FC<ComponentPropsWithRef<'polyline'> & XProps>;
  radialGradient: FC<ComponentPropsWithRef<'radialGradient'> & XProps>;
  rect: FC<ComponentPropsWithRef<'rect'> & XProps>;
  set: FC<ComponentPropsWithRef<'set'> & XProps>;
  stop: FC<ComponentPropsWithRef<'stop'> & XProps>;
  switch: FC<ComponentPropsWithRef<'switch'> & XProps>;
  symbol: FC<ComponentPropsWithRef<'symbol'> & XProps>;
  text: React.SVGTextElementAttributes<SVGTextElement>;
  textPath: FC<ComponentPropsWithRef<'textPath'> & XProps>;
  tspan: FC<ComponentPropsWithRef<'tspan'> & XProps>;
  use: FC<ComponentPropsWithRef<'use'> & XProps>;
  view: FC<ComponentPropsWithRef<'view'> & XProps>;

  // [TagName in keyof JSX.IntrinsicElements & string]: FC<
  //   ComponentPropsWithRef<TagName> & XProps
  // >;
} & {
  [key: string]: FC<
    HTMLAttributes<HTMLUnknownElement> &
      XProps & {
        ref?: RefObject<HTMLUnknownElement | undefined>;
      }
  >;
};
